defaults:
  run:
    shell: bash -l {0}

name: status-verification
run-name: checking if GESIS Notebook if operating
on:
  schedule:
    - cron:  '30 * * * *'
  workflow_dispatch:
jobs:
  pytest:
    runs-on: ubuntu-22.04
    env:
      SECRET_GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: requirements.prod.txt
          environment-name: orc2-status-bot
          channels: conda-forge
      - run: pytest --binder-url https://notebooks.gesis.org/binder/ --hub-url https://notebooks.gesis.org/binder/jupyter/ test
      - name: Upload build log artifact
        uses: actions/upload-artifact@v3
        with:
          name: build log
          path: build.log
          retention-days: 1
